# RL Policy Configuration
# Copyright 2024 Desay SV Automotive Co., Ltd.

# Vehicle parameters
vehicle:
  length: 4.8
  width: 2.0
  wheelbase: 2.8
  max_steering_angle: 0.48
  min_turning_radius: 6.0

# Observation parameters
observation:
  lidar:
    num_beams: 120
    max_range: 10.0
    fov: 6.28318530718  # 2*PI
  target:
    dimensions: 5
  image:
    width: 64
    height: 64
    channels: 3
    view_range: 20.0
    resolution: 0.3125  # view_range / max(width, height)
  action_mask:
    dimensions: 42
    num_steering_actions: 7
    num_step_lengths: 6
    min_steering: -1.0
    max_steering: 1.0
    min_step_length: 0.1
    max_step_length: 1.0

# RL model parameters
model:
  observation_dim: 12455
  action_dim: 2
  model_path: "actor_fixed.onnx"
  inference_engine: "onnx"  # "onnx" or "torch"

# Environment parameters
environment:
  max_episode_length: 1000
  collision_penalty: -100.0
  success_reward: 100.0
  step_penalty: -0.1
  target_reached_threshold: 0.5
  heading_error_threshold: 0.1

# Debug parameters
debug:
  enable_visualization: true
  save_trajectory: false
  log_level: "INFO"
  print_observation_stats: true
